package: 
  name: geospatial-learn
  version: 0.1

source:
  git_rev: v0.1
  git_url: https://github.com/Ciaran1981/geospatial-learn

requirements:
  build:
    - python
    - glob2
    - matplotlib
    - more-itertools
    - numpy
    - pandas
    - psutil
    - scikit-image
    - scikit-learn
    - scipy
    - gdal
    - tqdm

    
  run:
    - python
    - glob2
    - matplotlib
    - more-itertools
    - numpy
    - pandas
    - psutil
    - scikit-image
    - scikit-learn
    - scipy
    - gdal
    - tqdm

test:
  imports:
    - geospatial_learn

about:
  home: https://github.com/Ciaran1981/geospatial-learn
  license: GPLv3
  license_file: LICENSE
